
/*

Copyright © 2003-2013, Alexéy Sudachén, alexey@sudachen.name

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

*/

#if !defined __473E1AB8_C217_415D_885B_427068FD2ECF__
#define __473E1AB8_C217_415D_885B_427068FD2ECF__

#define MACRO_TEMPLATE_ARGUMENTS0
#define MACRO_TEMPLATE_FNTYPE_ARGUMENTS0
#define MACRO_TEMPLATE_FNDEF_ARGUMENTS0
#define MACRO_TEMPLATE_FNCALL_ARGUMENTS0

#define MACRO_TEMPLATE_ARGUMENTS1         class MACRO_A1
#define MACRO_TEMPLATE_FNTYPE_ARGUMENTS1  MACRO_A1
#define MACRO_TEMPLATE_FNDEF_ARGUMENTS1   MACRO_A1 MACRO_a1
#define MACRO_TEMPLATE_FNCALL_ARGUMENTS1  MACRO_a1

#define MACRO_TEMPLATE_ARGUMENTS2         MACRO_TEMPLATE_ARGUMENTS1,        class MACRO_A2
#define MACRO_TEMPLATE_FNTYPE_ARGUMENTS2  MACRO_TEMPLATE_FNTYPE_ARGUMENTS1, MACRO_A2
#define MACRO_TEMPLATE_FNDEF_ARGUMENTS2   MACRO_TEMPLATE_FNDEF_ARGUMENTS1,  MACRO_A2 MACRO_a2
#define MACRO_TEMPLATE_FNCALL_ARGUMENTS2  MACRO_TEMPLATE_FNCALL_ARGUMENTS1, MACRO_a2

#define MACRO_TEMPLATE_ARGUMENTS3         MACRO_TEMPLATE_ARGUMENTS2,        class MACRO_A3
#define MACRO_TEMPLATE_FNTYPE_ARGUMENTS3  MACRO_TEMPLATE_FNTYPE_ARGUMENTS2, MACRO_A3
#define MACRO_TEMPLATE_FNDEF_ARGUMENTS3   MACRO_TEMPLATE_FNDEF_ARGUMENTS2,  MACRO_A3 MACRO_a3
#define MACRO_TEMPLATE_FNCALL_ARGUMENTS3  MACRO_TEMPLATE_FNCALL_ARGUMENTS2, MACRO_a3

#define MACRO_TEMPLATE_ARGUMENTS4         MACRO_TEMPLATE_ARGUMENTS3,        class MACRO_A4
#define MACRO_TEMPLATE_FNTYPE_ARGUMENTS4  MACRO_TEMPLATE_FNTYPE_ARGUMENTS3, MACRO_A4
#define MACRO_TEMPLATE_FNDEF_ARGUMENTS4   MACRO_TEMPLATE_FNDEF_ARGUMENTS3,  MACRO_A4 MACRO_a4
#define MACRO_TEMPLATE_FNCALL_ARGUMENTS4  MACRO_TEMPLATE_FNCALL_ARGUMENTS3, MACRO_a4

#define MACRO_TEMPLATE_ARGUMENTS5         MACRO_TEMPLATE_ARGUMENTS4,        class MACRO_A5
#define MACRO_TEMPLATE_FNTYPE_ARGUMENTS5  MACRO_TEMPLATE_FNTYPE_ARGUMENTS4, MACRO_A5
#define MACRO_TEMPLATE_FNDEF_ARGUMENTS5   MACRO_TEMPLATE_FNDEF_ARGUMENTS4,  MACRO_A5 MACRO_a5
#define MACRO_TEMPLATE_FNCALL_ARGUMENTS5  MACRO_TEMPLATE_FNCALL_ARGUMENTS4, MACRO_a5

#define MACRO_TEMPLATE_ARGUMENTS6         MACRO_TEMPLATE_ARGUMENTS5,        class MACRO_A6
#define MACRO_TEMPLATE_FNTYPE_ARGUMENTS6  MACRO_TEMPLATE_FNTYPE_ARGUMENTS5, MACRO_A6
#define MACRO_TEMPLATE_FNDEF_ARGUMENTS6   MACRO_TEMPLATE_FNDEF_ARGUMENTS5,  MACRO_A6 MACRO_a6
#define MACRO_TEMPLATE_FNCALL_ARGUMENTS6  MACRO_TEMPLATE_FNCALL_ARGUMENTS5, MACRO_a6

#define MACRO_TEMPLATE_ARGUMENTS7         MACRO_TEMPLATE_ARGUMENTS6,        class MACRO_A7
#define MACRO_TEMPLATE_FNTYPE_ARGUMENTS7  MACRO_TEMPLATE_FNTYPE_ARGUMENTS6, MACRO_A7
#define MACRO_TEMPLATE_FNDEF_ARGUMENTS7   MACRO_TEMPLATE_FNDEF_ARGUMENTS6,  MACRO_A7 MACRO_a7
#define MACRO_TEMPLATE_FNCALL_ARGUMENTS7  MACRO_TEMPLATE_FNCALL_ARGUMENTS6, MACRO_a7

#define MACRO_TEMPLATE_ARGUMENTS8         MACRO_TEMPLATE_ARGUMENTS7,        class MACRO_A8
#define MACRO_TEMPLATE_FNTYPE_ARGUMENTS8  MACRO_TEMPLATE_FNTYPE_ARGUMENTS7, MACRO_A8
#define MACRO_TEMPLATE_FNDEF_ARGUMENTS8   MACRO_TEMPLATE_FNDEF_ARGUMENTS7,  MACRO_A8 MACRO_a8
#define MACRO_TEMPLATE_FNCALL_ARGUMENTS8  MACRO_TEMPLATE_FNCALL_ARGUMENTS7, MACRO_a8

#define MACRO_TEMPLATE_ARGUMENTS9         MACRO_TEMPLATE_ARGUMENTS8,        class MACRO_A9
#define MACRO_TEMPLATE_FNTYPE_ARGUMENTS9  MACRO_TEMPLATE_FNTYPE_ARGUMENTS8, MACRO_A9
#define MACRO_TEMPLATE_FNDEF_ARGUMENTS9   MACRO_TEMPLATE_FNDEF_ARGUMENTS8,  MACRO_A9 MACRO_a9
#define MACRO_TEMPLATE_FNCALL_ARGUMENTS9  MACRO_TEMPLATE_FNCALL_ARGUMENTS8, MACRO_a9

#endif // __473E1AB8_C217_415D_885B_427068FD2ECF__
